{"cells":[{"cell_type":"code","execution_count":3,"metadata":{},"outputs":[{"ename":"ImportError","evalue":"cannot import name 'datatime' from 'datetime' (c:\\Users\\pkong\\LSVM-XAUUSD\\venv\\lib\\datetime.py)","output_type":"error","traceback":["\u001b[1;31m---------------------------------------------------------------------------\u001b[0m","\u001b[1;31mImportError\u001b[0m                               Traceback (most recent call last)","Cell \u001b[1;32mIn[3], line 4\u001b[0m\n\u001b[0;32m      2\u001b[0m \u001b[39mimport\u001b[39;00m \u001b[39mpandas\u001b[39;00m \u001b[39mas\u001b[39;00m \u001b[39mpd\u001b[39;00m\n\u001b[0;32m      3\u001b[0m \u001b[39mimport\u001b[39;00m \u001b[39mplotly\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mexpress\u001b[39;00m \u001b[39mas\u001b[39;00m \u001b[39mpx\u001b[39;00m\n\u001b[1;32m----> 4\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mdatetime\u001b[39;00m \u001b[39mimport\u001b[39;00m datatime\n","\u001b[1;31mImportError\u001b[0m: cannot import name 'datatime' from 'datetime' (c:\\Users\\pkong\\LSVM-XAUUSD\\venv\\lib\\datetime.py)"]}],"source":["import MetaTrader5 as mt\n","import pandas as pd\n","import plotly.express as px\n","from datetime import datatime"]}],"metadata":{"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.9.0"},"orig_nbformat":4},"nbformat":4,"nbformat_minor":2}
